### ISSUE TITLE
Use odata version to 4.0 from 3.0

### ISSUE THREAD

**Issue by hozan23** [kamu-data/test-odata#5]
Hello,

Are there any plans to upgrade to OData version 4.0?

I would like to implement the filtering feature using [this library](https://crates.io/crates/odata-params), but it appears the library is built for OData version 4.0, not 3.0.

If there are plans for this upgrade, I would be happy to assist with the implementation and upgrade.

**Comment by sergiimk** [comment]
The system we needed to integrate with via OData API only supports OData v3, so we don't have a pressing need to support v4 at the moment.

The [list of changes](https://docs.oasis-open.org/odata/new-in-odata/v4.0/cn01/new-in-odata-v4.0-cn01.html) looks extensive and needs a proper investigation into how much effort it will be to support v4 within the very limited subset of features that we implement in this library. We would also need to define the maintenance strategy: do we support it as a branch, via conditional compilation, or need a fork.

In my eyes OData is a very niche protocol that is on a decline. I see a lot more momentum behind FlightSQL & ADBC technology stack which is where we will be focusing our efforts. If you are in control of both the client and the server - I would advise against using OData.

**Comment by hozan23** [comment]
Hey @sergiimk,

That makes sense. Unfortunately, we are trying to use OData with PowerBI, so our options are somewhat limited.

According to the list of changes you mentioned, it seems the $filter changes between v3 and v4 are relatively minor. We should still be able to implement the $filter functionality, possibly by using some features from OData v4. I believe it should remain backward compatible, right?

We’ve already started implementing the $filter feature, so in any case, we’ll go ahead and open a PR.

**Comment by hozan23** [comment]
Check the $filter implementation #9
